### ISSUE TITLE
FEAT: Using Ghostscript for reduce size of big PDFs 

### ISSUE THREAD

**Issue by gabolera** [sigalor/ghostscript-node#3]
It's maybe is interesting use this feature for reduce size of pdfs!

in my tests the results were very interesting, here is my simulation!

![Screenshot_36](https://user-images.githubusercontent.com/37487560/227048046-99c7a384-b3b8-443c-82e5-6e027de47214.png)

I used options of ghostscript for that

**Comment by gabolera** [comment]
@sigalor

**Comment by MedAzizKhayati** [comment]
Good job @gabolera
